site_name: 快手 · 音视频技术入门课

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  features:
    - navigation.footer
    - content.action.edit
    - navigation.sections
    - content.code.copy

  icon:
    edit: material/pencil
    logo: material/console-line

extra:
  homepage:
  version:
    provider: mike

copyright: Copyright © 2024-Present zkep
repo_url: https://github.com/zkep/mygeektime

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
   - 快手 · 音视频技术入门课.md
  
   - 开篇词-想快速入门音视频技术，你得这么学.md
  
   - 01-如何从色彩格式、帧率等参数角度看视频图像？.md
  
   - 02-音频从采集到输出涉及哪些关键参数？.md
  
   - 03-如何做音视频的封装与转码？.md
  
   - 04-直播行业的发展概况与技术迭代.md
  
   - 05-如何使用 FFmpeg 与 OBS 进行直播推流？.md
  
   - 06-如何使用 ffprobe 分析音视频参数与内容？.md
  
   - 07 - 如何高效查找并使用FFmpeg常用参数？.md
  
   - 08-FFmpeg 和它的朋友们是怎么处理 MP4 的？.md
  
   - 09-如何使用 FFmpeg 与 Handbrake 做转码？.md
  
   - 10 - FFmpeg 基础模块（一）：容器相关的 API 操作.md
  
   - 11 - FFmpeg 基础模块（二）：AVIO、AVDictionary 与 AVOption.md
  
   - 12 - FFmpeg基础模块（三）：AVCodec.md
  
   - 13 - FFmpeg 有哪些常见的应用场景？.md
  
   - 14-如何在FFmpeg中定制一个自己专属的模块？.md
  
   - 15-如何参与到FFmpeg社区交流中？.md
  
   - 结束语-音视频技术更宠爱脚踏实地的人.md
  
   - 期末测试-来赴一场满分之约！.md
  